package com.example.alfamessanger.utills.enums

enum class BottomSheetSettings {
    ACCOUNT_BOTTOM_SHEET,
    CHAT_BOTTOM_SHEET,
    FULL_SCREEN_IMAGE_SAVED,
    FULL_SCREEN_IMAGE_NOT_SAVED,
    GRAFFITI_BOTTOM_SHEET,
    ADMIN_CREATE_NEWS_BOTTOM_SHEET,
    ADMIN_CHANNEL_MAIN_BOTTOM_SHEET,
    WATCHER_CHANNEL_MAIN_BOTTOM_SHEET,
    SUBSCRIBER_CHANNEL_MAIN_BOTTOM_SHEET
}